[package]
name = "gpodderid3"
version = "0.1.0"
authors = ["Christof Damian <christof@damian.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rusqlite = "0.28"
id3 = "1.6"
clap = "4.1"
